version: "3"

services:
  app:
    volumes:
      - ./:/usr/src/app/
    build:
      context: .
    tty: true
    command: sh -c "npm install && npm start"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - 3000:3000
